# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Account and publish issues', '\u0645\u0634\u0627\u0643\u0644 \u0627\u0644\u062d\u0633\u0627\u0628 \u0648 \u0627\u0644\u0646\u0634\u0631'), ('Rules violence', '\u0627\u0644\u0625\u0628\u0644\u0627\u063a \u0639\u0646 \u0627\u0646\u062a\u0647\u0627\u0643 \u0644\u0644\u0642\u0648\u0627\u0639\u062f'), ('DMCA and Copyright', '\u0642\u0636\u0627\u064a\u0627 DMCA / \u062d\u0642\u0648\u0642 \u0627\u0644\u0637\u0628\u0639 \u0648\u0627\u0644\u0646\u0634\u0631'), ('FeedBack and other', '\u0631\u062f\u0648\u062f \u0627\u0644\u0641\u0639\u0644 \u0623\u0648 \u0645\u0634\u0627\u0643\u0644 \u0623\u062e\u0631\u0649')], default='Account and publish issues', max_length=300)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
