# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 15:04
from __future__ import unicode_literals

import Profiles.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, validators=[Profiles.validators.is_fname])),
                ('last_name', models.CharField(default='', max_length=100, validators=[Profiles.validators.is_fname])),
                ('email', models.EmailField(default='', max_length=100)),
                ('avatar', sorl.thumbnail.fields.ImageField(default='avatars/alien.png', upload_to='avatars', verbose_name='\u0635\u0648\u0631\u0629 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645')),
                ('bio', models.CharField(blank=True, default='', max_length=200, verbose_name='\u0639\u0646 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
